---
output: html_document
---

This is a basic visualization and summary of the data collected by Dr. Alex Bond and Auriel Fournier. 

As of ```date()``` this repo and file are still being constructed. Our end goal is to update this once monthly with summaries of technician positions from the following job boards to look at trends over time and help raise awareness about the frequency of these positions. 

Job boards:

Texas A&M (last updated August 2015)
BirdJobs (last updated December 3, 2015)



```{r}
library(ggplot2)
library(auriel) #Auriel's personal R package https://github.com/aurielfournier/rel
jobs <- read.csv("~/unpaid_technicians/ongoing_collection.csv")

ggplot()+
  geom_bar(data=jobs, aes(x=month, y=percentage, fill=type), stat="identity")
```


paid = paid > $300 USD/month
unpaid = paid < $300 USD/month
pay_to_work = technician pays them to 'work' 
unclear = no mention of salary was made or 'based on experience' or other such text were used

This summary includes only season technician level positions. Not full time permanent jobs, or jobs requiring a graduate level degree. Though we have seen some of those being unpaid as well. 